### ISSUE TITLE
Disable ActivationHotKey

### ISSUE THREAD

**Issue by marconetto** [FancyWM/fancywm#151]
I understand the ActivationHotKey can help if we forget some shortcut.

I'm trying to configure a hyperkey (capslock mapped to win+shift+alt+control via ahk) and it seems it is also triggering the activationhotkey of fancywm. Is there any way disable the ActivationHotKey?

**Comment by riotrah** [comment]
I have this problem sometimes - I'm not sure why it's not consistent. 

How are you setting up your hyper key? AHK?

**Comment by marconetto** [comment]
Yes using AHK as described in the highest score answer in this thread:
https://stackoverflow.com/questions/40435980/how-to-emulate-hyper-key-in-windows-10-using-autohotkey

My experience is that using hyper this way, I think all times fancywm makes the border of the current window be colored when pressed and some times the activationhotkey menu shows up. That is why I would very much like to disable the activationhotkey.

What I ended up doing, which is 'ok' for now (I'm sure it will conflict with something in near future), is to have my hyper only with alt+control+win. This way I don't have conflict with fancywm.  I'm new to windows (always used linux+mac) / ahk / fancywm.

**Comment by riotrah** [comment]
@marconetto 

Yeah I've been using a Mac for work for about a year now and that's where I got into hyper key stuff via karabiner. In case it's similar to yours, my desired config is basically:

1. Tap capslock for escape
2. Hold capslock for `hyper` = `win+shift+ctrl+alt`
3. Except for special keys: `hjkl`, `ui`, `pn`, which emit `arrows`, `pgUp/Down`, `home/end` respectively - such that `<modifier>+capslock+<special key>` also "passes through" any extra modifiers as well, as if I'd pressed `<modifier>+<special key mapping>`

Porting that to Windows has been more tricky than I'd expected. Using `ahk` for my particular use case didn't end up working exactly as I'd wanted, so I moved to `Kanata` for just the key remapping + `ahk` for doing anything else with those keys.

I've found that when I was first setting up both `ahk` and `Kanata` that I'd accidentally activate FWM any time I'd press `capslock`. However - and I unfortunately can't remember _exactly_ how - I was able to get past that problem. Perhaps I had to ensure that either `ahk` or `Kanata` were started as admin? Try that if you haven't already. 

I'm gonna edit this comment with a link to my old ahk config and my post on Kanata's repo where I asked and received help for my personal approach to caps lock hyper key, lemme know if they help. 

---

Strangely, even though I've fixed the accidental fwm activation, FancyWM is the **only** application that can somehow "see through" the remapping, which means that if `capslock+h` = `left arrow`, and I do:
1. `win+shift` -> activate fwm
2. `capslock+h` -> `left`

FancyWM does not receive a `left` but in fact does receive a `capslock+h`! Which is remarkable because Windows itself and the rest of the UI of the system or any app thinks I pressed `left` as intended. Very strange!

--_
