### ISSUE TITLE
Cycle focus through monitors + cycle (move) window through monitors

### ISSUE THREAD

**Issue by Huray-hub** [FancyWM/fancywm#161]
**Describe the solution you'd like**
In [dwm](https://dwm.suckless.org/), I can move focus to next monitor clock-wise (monitor 1 -> monitor 2 -> monitor 3) using Alt+. and counter clock-wise using Alt+, . I also move focused window with the same pattern using Alt+Shift+, and Alt+Shift+. .

Is it possible with FancyWM? How?

If it's not, it would be a good feature to be added.

**Comment by kirpy0x** [comment]
This would be great because sometimes I use 2 displays and sometimes 3. As I open/close my laptop screen while docked or undock/redock the display numbers seem unpredictable and get unpredictable keybinding assignments. It would probably be best to just cycle through them. Cycling based on direction would be best if possible but even if the directions not consistant having an option to cycle would be nice.
