### ISSUE TITLE
Missing keybinding for switch to next desktop and move window to next desktop

### ISSUE THREAD

**Issue by iuriSpinassi** [FancyWM/fancywm#276]
**Describe the bug**
I didn't find the option to move and switch window to next desktop. Just to the previous one.

**To Reproduce**
1. Open Keybindings section
2. Search for "Switch to next desktop" and "Move window to next desktop"

**Expected behavior**
Find the "next" options

**Desktop (please complete the following information):**
- OS: Windows 10
- OS Build: 19045
- FancyWM Version: 2.14.0.0

**Comment by veselink1** [comment]
`Switch/move to previous desktop` possibly needs to be renamed. Previous here means the desktop that was last focused, not the desktop that is before the current one in the order that Windows presents them in the task view. 

If you move from desktop 1 to desktop 2, previous desktop is 1. If you move back from 2 to 1, the previous desktop will be desktop 2.

What is the expected behaviour for the "switch to next desktop"?
