### ISSUE TITLE
Layout presets

### ISSUE THREAD

**Issue by sp4d1n0** [FancyWM/fancywm#4]
**Is your feature request related to a problem? Please describe.**
Manually have to resize layout

**Describe the solution you'd like**
Setup some layouts to be assigned to a monitor, as fancyzone, and able to be recalled by keybinds

**Describe alternatives you've considered**
None

**Additional context**
Been able to use the same layouts as fancyzone would be great, as fancyzone already has the ability to setup more than a layout for the same monitor and to recall them by keybind

**Comment by aspidxt** [comment]
I want to extend this discussion a little bit. 

So main idea behind this (as well as couple others) ticket here is to be able to store current layout configuration and restore it later.
It's kind of partially working even right now, when you minimize window and then activate it again it returns back to same panel, same place (if window not alone in group). 
You can use Win + Number keys to minimize/restore windows from taskbar and check it

It's not possible to restore window in same place if it was only window in group, because if all windows leave group it's removed automatically.

So you may:
- allow groups to live without windows (auto add some placeholder if group is empty)
- add hotkey to drop group (if focus on this placeholder, for ex)
- serialize layout state and restore when app launches
