### ISSUE TITLE
Define defaults for specific programs

### ISSUE THREAD

**Issue by sp4d1n0** [FancyWM/fancywm#5]
**Is your feature request related to a problem? Please describe.**
Programs and dialog do not remember their states

**Describe the solution you'd like**
I would like to be able to define programs which also will run in a specific way (stacked, floating...)

**Comment by gustavoholst** [comment]
@veselink1 - Just started using the program yesterday! Like it so far.
I don't think #4 describes how specific programs will interact with each preset (at least not at the moment), just that there will be predefined sets of stacks/splits that can be recalled. 

For me, I think certain programs should have certain default behaviors, in addition to the floating mode by default. Things like:
- chat program default width, so that when it launches and the screen splits to accommodate, it only takes up 25% of the screen instead of the default 50%
- certain windows always going to the largest or smallest available stack
- pairs or groups of windows that you want to form up together when launched
- etc.

Thoughts?

**Comment by whaaaley** [comment]
+1 For this. I just installed today and it's great so far! It would be nice to have processes remember the last stack they were a part of instead of starting from scratch every time you reopen an application or restart your PC.

**Comment by paulius-valiunas** [comment]
I think the bot closed this issue too soon. I would love this feature, especially when I reboot my computer and all the autostart apps show up in a completely messed up layout.
