### ISSUE TITLE
Reserve empty space for the default layout

### ISSUE THREAD

**Issue by airens** [FancyWM/fancywm#60]
**Is your feature request related to a problem? Please describe.**
I'm using the big 34' ultra-wide monitor and when I start the first app on the desktop it opens up to the full with of my monitor (despite "Reserve Empty Space in New Panels" option), which looks really ugly:
![image](https://user-images.githubusercontent.com/45446974/155554952-96f0941d-bcdc-4046-9d2a-8873fecdd063.png)

**Describe the solution you'd like**
Would be great, if the "Reserve Empty Space in New Panels" option also worked on default layout

**Describe alternatives you've considered**
Also it would be great if the new window could be center aligned which looks much better than left aligned variant:

![image](https://user-images.githubusercontent.com/45446974/155555704-e0db6fe0-7c30-419b-9ce7-901d56b5d5d0.png)

**Additional context**
Thanks a lot for the app!

**Comment by veselink1** [comment]
Thanks for the feature request. With "Reserve Empty Space in New Panels" the empty space is temporarily reserved, serving as a visual indication of the panel layout. If you add a second window to the panel, and then close that second window, the empty space will have disappeared. 

I'm only pointing this out because I feel that the behaviour you are looking for might be better expressed as a limit on the initial window size. For example "Initial window size limit" = 50%, would never allow new windows to take up more than 50% of the screen width, achieving the outcome you are looking for. Please indicate whether that would be preferable, thanks.

**Comment by haininhhoang94** [comment]
please implement this feature, i really need it !

**Comment by majidaldo** [comment]
same. with wide monitors, it's best to think of the middle third or so as the focus area.

**Comment by snize** [comment]
@veselink1 In keeping with the dynamic tiling window manager concept, I have a suggestion to tackle the issue by limiting the maximum size of each panel. 

For instance, if the screen width is 5K (5120) and we limit the maximum size per panel to 1920, we'll have 1600 pixels of space left on both sides when there's only one panel. If we have two panels, there'll be 640 pixels of space left on both sides. And with three panels, there won't be any empty space left, making the layout pretty similar to the normal mode.

The cool thing about this idea is that when the number of panels goes down, we still have space on both sides, so users won't have to deal with panels that get way too big.
